### ISSUE TITLE
Calendar desyncs after 10th day of some months.

### ISSUE THREAD

**Issue by thompson-vii** [vipzhicheng/logseq-plugin-block-calendar#17]
win10, logseq ver 0.8.5, block calendar 0.1.5

https://user-images.githubusercontent.com/31672176/189723480-c0453121-8d67-4dd4-ba50-6682bf53aff9.mp4

**Comment by bobmhughes** [comment]
I have exactly the same issue using Block Calendar v 0.1.7 in Logseq 0.8.8 using both a Windows 10 pc (OS Build 19044.2006) and a MacBook Pro M1 running Monterey 12.6. Can anyone else reproduce this issue?

**Comment by scfcode** [comment]
+1, seeing the same issue using Block Calendar v 0.1.7 in Logseq 0.8.8 using a MacBook Pro Intel, running Monterey 12.6.

**Comment by vipzhicheng** [comment]
has been fixed, please upgrade.

**Comment by thompson-vii** [comment]
https://user-images.githubusercontent.com/31672176/208161748-504ab2b7-2ab4-43da-9951-7600c9b47ea2.mp4

still broken, 0.1.11

**Comment by bobmhughes** [comment]
Thank you for attempting to fix this issue, however I confirm what thompson-vii noted. January through September work correctly, but October, November and December are out of sync by one day starting with the 10th of the month up to the end of the month. So, for example. when I click on December 10th, December 9th is displayed; when I click on December 11th, December 10th is displayed; and so on, right up to when I click on Dec. 31, December 30th is displayed. The same is true for all days in October, November & December from the 10tth of the month through the end of the month.

**Comment by bobmhughes** [comment]
As of today, February 9, 2023 using Block Calendar version 0.2.2, this issue still persists. 

On Dec. 16, 2022 I wrote "Thank you for attempting to fix this issue, however I confirm what thompson-vii noted. January through September work correctly, but October, November and December are out of sync by one day starting with the 10th of the month up to the end of the month. So, for example. when I click on December 10th, December 9th is displayed; when I click on December 11th, December 10th is displayed; and so on, right up to when I click on Dec. 31, December 30th is displayed. The same is true for all days in October, November & December from the 10tth of the month through the end of the month."

**Comment by vipzhicheng** [comment]
I thought I had fixed this issue, but seems still have issues.

I can not reproduce this issue on my local, so please run the code below in your computer browser console to see which timezone you are in.

```
Intl.DateTimeFormat().resolvedOptions().timeZone
```

**Comment by bobmhughes** [comment]
I don’t know how to run the code in my computer browser console, but I know that my time zone is as follows:
Pacific Standard time UTC-07:00 from the first Sunday in November until the second Sunday in March
Pacific Daylight time UTC-08:00 from the Second Sunday in March until the first Sunday in November

Thanks for your help.

Bob



From: Richard Yu ***@***.***>
Date: Thursday, February 9, 2023 at 9:30 PM
To: vipzhicheng/logseq-plugin-block-calendar ***@***.***>
Cc: bobmhughes ***@***.***>, Manual ***@***.***>
Subject: Re: [vipzhicheng/logseq-plugin-block-calendar] Calendar desyncs after 10th day of some months. (Issue #17)

I thought I had fixed this issue, but seems still have issues.

I can not reproduce this issue on my local, so please run the code below in your computer browser console to see which timezone you are in.

Intl.DateTimeFormat().resolvedOptions().timeZone

**Comment by thompson-vii** [comment]
'America/Chicago'

**Comment by vipzhicheng** [comment]
v0.2.3 is a small fix, but I don't know if it works, please have a test.

**Comment by bobmhughes** [comment]
Hello Richard,

I just installed 0.2.3, and unfortunately, there is no change for October, November or December.

Thanks for continuing to work on this issue.

Let me know if there is anything else I can do to help.

Bob

From: Richard Yu ***@***.***>
Date: Sunday, February 12, 2023 at 7:39 PM
To: vipzhicheng/logseq-plugin-block-calendar ***@***.***>
Cc: bobmhughes ***@***.***>, Manual ***@***.***>
Subject: Re: [vipzhicheng/logseq-plugin-block-calendar] Calendar desyncs after 10th day of some months. (Issue #17)

v0.2.3 is a small fix, but I don't know if it works, please have a test.

**Comment by vipzhicheng** [comment]
Please try again. Because I can not reproduce it on my local. I have no idea what is wrong. So I can only try to fix it by guessing. 😭

**Comment by bobmhughes** [comment]
Hi Richard,

I am pleased to report that you have solved this issue with version 0.2.4!

Many thanks!

Bob

From: Richard Yu ***@***.***>
Date: Sunday, February 12, 2023 at 8:27 PM
To: vipzhicheng/logseq-plugin-block-calendar ***@***.***>
Cc: bobmhughes ***@***.***>, Manual ***@***.***>
Subject: Re: [vipzhicheng/logseq-plugin-block-calendar] Calendar desyncs after 10th day of some months. (Issue #17)

Please try again. Because I can not reproduce it on my local. I have no idea what is wrong. So I can only try to fix it by guessing. 😭

**Comment by thompson-vii** [comment]
It is indeed fixed in 0.2.4. Thank you for your hardwork Richard :)
